/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.exTwentyOne;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.exTwentyOne.ExTwentyOneFactory
 * @model kind="package"
 * @generated
 */
public interface ExTwentyOnePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "exTwentyOne";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/ExTwentyOne";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "exTwentyOne";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ExTwentyOnePackage eINSTANCE = org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ProgramImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__DECLARATIONS = 1;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.DeclarationImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 1;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ParameterImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.FunctionImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Lambda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__LAMBDA = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ElementImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 8;

  /**
   * The feature id for the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NODE = 1;

  /**
   * The feature id for the '<em><b>Output</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__OUTPUT = 2;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.LambdaImpl <em>Lambda</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.LambdaImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getLambda()
   * @generated
   */
  int LAMBDA = 4;

  /**
   * The feature id for the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__ELEMENT = ELEMENT__ELEMENT;

  /**
   * The feature id for the '<em><b>Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__NODE = ELEMENT__NODE;

  /**
   * The feature id for the '<em><b>Output</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__OUTPUT = ELEMENT__OUTPUT;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Lambda Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__LAMBDA_EXP = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Lambda</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.InputImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getInput()
   * @generated
   */
  int INPUT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.NodeImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getNode()
   * @generated
   */
  int NODE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__FUNCTION = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Lambda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__LAMBDA = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.StreamImpl <em>Stream</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.StreamImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getStream()
   * @generated
   */
  int STREAM = 7;

  /**
   * The feature id for the '<em><b>Inputs Or Nodes</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STREAM__INPUTS_OR_NODES = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STREAM__ELEMENTS = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Stream</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STREAM_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.DataDeclImpl <em>Data Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.DataDeclImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getDataDecl()
   * @generated
   */
  int DATA_DECL = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_DECL__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Data</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_DECL__DATA = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Data Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_DECL_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.InputOrNodeImpl <em>Input Or Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.InputOrNodeImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getInputOrNode()
   * @generated
   */
  int INPUT_OR_NODE = 10;

  /**
   * The feature id for the '<em><b>Input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_OR_NODE__INPUT = 0;

  /**
   * The feature id for the '<em><b>Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_OR_NODE__NODE = 1;

  /**
   * The number of structural features of the '<em>Input Or Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_OR_NODE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ExpImpl <em>Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExpImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getExp()
   * @generated
   */
  int EXP = 11;

  /**
   * The feature id for the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__LEFT = 0;

  /**
   * The feature id for the '<em><b>Right Plus</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__RIGHT_PLUS = 1;

  /**
   * The feature id for the '<em><b>Right Minus</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__RIGHT_MINUS = 2;

  /**
   * The feature id for the '<em><b>Right Multiply</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__RIGHT_MULTIPLY = 3;

  /**
   * The feature id for the '<em><b>Right Divide</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__RIGHT_DIVIDE = 4;

  /**
   * The feature id for the '<em><b>In Parenthesis</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__IN_PARENTHESIS = 5;

  /**
   * The feature id for the '<em><b>Let Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__LET_ID = 6;

  /**
   * The feature id for the '<em><b>Let Def Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__LET_DEF_EXP = 7;

  /**
   * The feature id for the '<em><b>Let Target Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__LET_TARGET_EXP = 8;

  /**
   * The feature id for the '<em><b>If Logic Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__IF_LOGIC_EXP = 9;

  /**
   * The feature id for the '<em><b>Then Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__THEN_EXP = 10;

  /**
   * The feature id for the '<em><b>Else Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__ELSE_EXP = 11;

  /**
   * The feature id for the '<em><b>New Array Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__NEW_ARRAY_ID = 12;

  /**
   * The feature id for the '<em><b>New Array Ids</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__NEW_ARRAY_IDS = 13;

  /**
   * The feature id for the '<em><b>New Array Exps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__NEW_ARRAY_EXPS = 14;

  /**
   * The number of structural features of the '<em>Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_FEATURE_COUNT = 15;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.LogicExpImpl <em>Logic Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.LogicExpImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getLogicExp()
   * @generated
   */
  int LOGIC_EXP = 12;

  /**
   * The feature id for the '<em><b>Left Logic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP__LEFT_LOGIC = 0;

  /**
   * The feature id for the '<em><b>Right Logic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP__RIGHT_LOGIC = 1;

  /**
   * The number of structural features of the '<em>Logic Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Program#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Program#getName()
   * @see #getProgram()
   * @generated
   */
  EAttribute getProgram_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.exTwentyOne.Program#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Program#getDeclarations()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Declarations();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Function#getLambda <em>Lambda</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lambda</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Function#getLambda()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Lambda();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Lambda <em>Lambda</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lambda</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Lambda
   * @generated
   */
  EClass getLambda();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Lambda#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Lambda#getName()
   * @see #getLambda()
   * @generated
   */
  EAttribute getLambda_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Lambda#getLambdaExp <em>Lambda Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lambda Exp</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Lambda#getLambdaExp()
   * @see #getLambda()
   * @generated
   */
  EReference getLambda_LambdaExp();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Input#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Input#getName()
   * @see #getInput()
   * @generated
   */
  EAttribute getInput_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Node#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Node#getName()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.exTwentyOne.Node#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Function</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Node#getFunction()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Function();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Node#getLambda <em>Lambda</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lambda</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Node#getLambda()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Lambda();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Stream <em>Stream</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stream</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Stream
   * @generated
   */
  EClass getStream();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.exTwentyOne.Stream#getInputsOrNodes <em>Inputs Or Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Inputs Or Nodes</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Stream#getInputsOrNodes()
   * @see #getStream()
   * @generated
   */
  EReference getStream_InputsOrNodes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.exTwentyOne.Stream#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Stream#getElements()
   * @see #getStream()
   * @generated
   */
  EReference getStream_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Element#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Element</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Element#getElement()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Element();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.exTwentyOne.Element#getNode <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Node</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Element#getNode()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Node();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Element#getOutput <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Output</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Element#getOutput()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Output();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.DataDecl <em>Data Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Decl</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.DataDecl
   * @generated
   */
  EClass getDataDecl();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.DataDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.DataDecl#getName()
   * @see #getDataDecl()
   * @generated
   */
  EAttribute getDataDecl_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.exTwentyOne.DataDecl#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Data</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.DataDecl#getData()
   * @see #getDataDecl()
   * @generated
   */
  EAttribute getDataDecl_Data();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.InputOrNode <em>Input Or Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input Or Node</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.InputOrNode
   * @generated
   */
  EClass getInputOrNode();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.InputOrNode#getInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Input</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.InputOrNode#getInput()
   * @see #getInputOrNode()
   * @generated
   */
  EReference getInputOrNode_Input();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.InputOrNode#getNode <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Node</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.InputOrNode#getNode()
   * @see #getInputOrNode()
   * @generated
   */
  EReference getInputOrNode_Node();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Exp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp
   * @generated
   */
  EClass getExp();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getLeft()
   * @see #getExp()
   * @generated
   */
  EAttribute getExp_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getRightPlus <em>Right Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right Plus</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getRightPlus()
   * @see #getExp()
   * @generated
   */
  EReference getExp_RightPlus();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getRightMinus <em>Right Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right Minus</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getRightMinus()
   * @see #getExp()
   * @generated
   */
  EReference getExp_RightMinus();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getRightMultiply <em>Right Multiply</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right Multiply</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getRightMultiply()
   * @see #getExp()
   * @generated
   */
  EReference getExp_RightMultiply();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getRightDivide <em>Right Divide</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right Divide</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getRightDivide()
   * @see #getExp()
   * @generated
   */
  EReference getExp_RightDivide();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getInParenthesis <em>In Parenthesis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>In Parenthesis</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getInParenthesis()
   * @see #getExp()
   * @generated
   */
  EReference getExp_InParenthesis();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getLetId <em>Let Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Let Id</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getLetId()
   * @see #getExp()
   * @generated
   */
  EAttribute getExp_LetId();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getLetDefExp <em>Let Def Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Let Def Exp</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getLetDefExp()
   * @see #getExp()
   * @generated
   */
  EReference getExp_LetDefExp();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getLetTargetExp <em>Let Target Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Let Target Exp</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getLetTargetExp()
   * @see #getExp()
   * @generated
   */
  EReference getExp_LetTargetExp();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getIfLogicExp <em>If Logic Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>If Logic Exp</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getIfLogicExp()
   * @see #getExp()
   * @generated
   */
  EReference getExp_IfLogicExp();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getThenExp <em>Then Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then Exp</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getThenExp()
   * @see #getExp()
   * @generated
   */
  EReference getExp_ThenExp();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getElseExp <em>Else Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else Exp</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getElseExp()
   * @see #getExp()
   * @generated
   */
  EReference getExp_ElseExp();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getNewArrayId <em>New Array Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>New Array Id</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getNewArrayId()
   * @see #getExp()
   * @generated
   */
  EAttribute getExp_NewArrayId();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getNewArrayIds <em>New Array Ids</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>New Array Ids</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getNewArrayIds()
   * @see #getExp()
   * @generated
   */
  EAttribute getExp_NewArrayIds();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.exTwentyOne.Exp#getNewArrayExps <em>New Array Exps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>New Array Exps</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Exp#getNewArrayExps()
   * @see #getExp()
   * @generated
   */
  EReference getExp_NewArrayExps();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.LogicExp <em>Logic Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logic Exp</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.LogicExp
   * @generated
   */
  EClass getLogicExp();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.LogicExp#getLeftLogic <em>Left Logic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left Logic</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.LogicExp#getLeftLogic()
   * @see #getLogicExp()
   * @generated
   */
  EReference getLogicExp_LeftLogic();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.LogicExp#getRightLogic <em>Right Logic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right Logic</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.LogicExp#getRightLogic()
   * @see #getLogicExp()
   * @generated
   */
  EReference getLogicExp_RightLogic();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ExTwentyOneFactory getExTwentyOneFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ProgramImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM__NAME = eINSTANCE.getProgram_Name();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__DECLARATIONS = eINSTANCE.getProgram_Declarations();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.DeclarationImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ParameterImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.FunctionImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '<em><b>Lambda</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__LAMBDA = eINSTANCE.getFunction_Lambda();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.LambdaImpl <em>Lambda</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.LambdaImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getLambda()
     * @generated
     */
    EClass LAMBDA = eINSTANCE.getLambda();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LAMBDA__NAME = eINSTANCE.getLambda_Name();

    /**
     * The meta object literal for the '<em><b>Lambda Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAMBDA__LAMBDA_EXP = eINSTANCE.getLambda_LambdaExp();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.InputImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT__NAME = eINSTANCE.getInput_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.NodeImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__NAME = eINSTANCE.getNode_Name();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__FUNCTION = eINSTANCE.getNode_Function();

    /**
     * The meta object literal for the '<em><b>Lambda</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__LAMBDA = eINSTANCE.getNode_Lambda();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.StreamImpl <em>Stream</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.StreamImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getStream()
     * @generated
     */
    EClass STREAM = eINSTANCE.getStream();

    /**
     * The meta object literal for the '<em><b>Inputs Or Nodes</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STREAM__INPUTS_OR_NODES = eINSTANCE.getStream_InputsOrNodes();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STREAM__ELEMENTS = eINSTANCE.getStream_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ElementImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__ELEMENT = eINSTANCE.getElement_Element();

    /**
     * The meta object literal for the '<em><b>Node</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__NODE = eINSTANCE.getElement_Node();

    /**
     * The meta object literal for the '<em><b>Output</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__OUTPUT = eINSTANCE.getElement_Output();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.DataDeclImpl <em>Data Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.DataDeclImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getDataDecl()
     * @generated
     */
    EClass DATA_DECL = eINSTANCE.getDataDecl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_DECL__NAME = eINSTANCE.getDataDecl_Name();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_DECL__DATA = eINSTANCE.getDataDecl_Data();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.InputOrNodeImpl <em>Input Or Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.InputOrNodeImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getInputOrNode()
     * @generated
     */
    EClass INPUT_OR_NODE = eINSTANCE.getInputOrNode();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INPUT_OR_NODE__INPUT = eINSTANCE.getInputOrNode_Input();

    /**
     * The meta object literal for the '<em><b>Node</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INPUT_OR_NODE__NODE = eINSTANCE.getInputOrNode_Node();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ExpImpl <em>Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExpImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getExp()
     * @generated
     */
    EClass EXP = eINSTANCE.getExp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXP__LEFT = eINSTANCE.getExp_Left();

    /**
     * The meta object literal for the '<em><b>Right Plus</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__RIGHT_PLUS = eINSTANCE.getExp_RightPlus();

    /**
     * The meta object literal for the '<em><b>Right Minus</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__RIGHT_MINUS = eINSTANCE.getExp_RightMinus();

    /**
     * The meta object literal for the '<em><b>Right Multiply</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__RIGHT_MULTIPLY = eINSTANCE.getExp_RightMultiply();

    /**
     * The meta object literal for the '<em><b>Right Divide</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__RIGHT_DIVIDE = eINSTANCE.getExp_RightDivide();

    /**
     * The meta object literal for the '<em><b>In Parenthesis</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__IN_PARENTHESIS = eINSTANCE.getExp_InParenthesis();

    /**
     * The meta object literal for the '<em><b>Let Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXP__LET_ID = eINSTANCE.getExp_LetId();

    /**
     * The meta object literal for the '<em><b>Let Def Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__LET_DEF_EXP = eINSTANCE.getExp_LetDefExp();

    /**
     * The meta object literal for the '<em><b>Let Target Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__LET_TARGET_EXP = eINSTANCE.getExp_LetTargetExp();

    /**
     * The meta object literal for the '<em><b>If Logic Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__IF_LOGIC_EXP = eINSTANCE.getExp_IfLogicExp();

    /**
     * The meta object literal for the '<em><b>Then Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__THEN_EXP = eINSTANCE.getExp_ThenExp();

    /**
     * The meta object literal for the '<em><b>Else Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__ELSE_EXP = eINSTANCE.getExp_ElseExp();

    /**
     * The meta object literal for the '<em><b>New Array Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXP__NEW_ARRAY_ID = eINSTANCE.getExp_NewArrayId();

    /**
     * The meta object literal for the '<em><b>New Array Ids</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXP__NEW_ARRAY_IDS = eINSTANCE.getExp_NewArrayIds();

    /**
     * The meta object literal for the '<em><b>New Array Exps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP__NEW_ARRAY_EXPS = eINSTANCE.getExp_NewArrayExps();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.LogicExpImpl <em>Logic Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.LogicExpImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getLogicExp()
     * @generated
     */
    EClass LOGIC_EXP = eINSTANCE.getLogicExp();

    /**
     * The meta object literal for the '<em><b>Left Logic</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGIC_EXP__LEFT_LOGIC = eINSTANCE.getLogicExp_LeftLogic();

    /**
     * The meta object literal for the '<em><b>Right Logic</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGIC_EXP__RIGHT_LOGIC = eINSTANCE.getLogicExp_RightLogic();

  }

} //ExTwentyOnePackage
