/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.exTwentyOne;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.exTwentyOne.ExTwentyOneFactory
 * @model kind="package"
 * @generated
 */
public interface ExTwentyOnePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "exTwentyOne";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/ExTwentyOne";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "exTwentyOne";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ExTwentyOnePackage eINSTANCE = org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ProgramImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__DECLARATIONS = 1;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.DeclarationImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 1;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ParameterImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.FunctionImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Lambda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__LAMBDA = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ElementImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 8;

  /**
   * The feature id for the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NODE = 1;

  /**
   * The feature id for the '<em><b>Output</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__OUTPUT = 2;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.LambdaImpl <em>Lambda</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.LambdaImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getLambda()
   * @generated
   */
  int LAMBDA = 4;

  /**
   * The feature id for the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__ELEMENT = ELEMENT__ELEMENT;

  /**
   * The feature id for the '<em><b>Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__NODE = ELEMENT__NODE;

  /**
   * The feature id for the '<em><b>Output</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__OUTPUT = ELEMENT__OUTPUT;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Lambda Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__LAMBDA_EXP = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Lambda</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.InputImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getInput()
   * @generated
   */
  int INPUT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.NodeImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getNode()
   * @generated
   */
  int NODE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__FUNCTION = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Lambda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__LAMBDA = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.StreamImpl <em>Stream</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.StreamImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getStream()
   * @generated
   */
  int STREAM = 7;

  /**
   * The feature id for the '<em><b>Inputs Or Nodes</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STREAM__INPUTS_OR_NODES = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STREAM__ELEMENTS = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Stream</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STREAM_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.DataDeclImpl <em>Data Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.DataDeclImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getDataDecl()
   * @generated
   */
  int DATA_DECL = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_DECL__NAME = DECLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Data</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_DECL__DATA = DECLARATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Data Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_DECL_FEATURE_COUNT = DECLARATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.InputOrNodeImpl <em>Input Or Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.InputOrNodeImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getInputOrNode()
   * @generated
   */
  int INPUT_OR_NODE = 10;

  /**
   * The number of structural features of the '<em>Input Or Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_OR_NODE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.NodeOrFunctionImpl <em>Node Or Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.NodeOrFunctionImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getNodeOrFunction()
   * @generated
   */
  int NODE_OR_FUNCTION = 11;

  /**
   * The number of structural features of the '<em>Node Or Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_OR_FUNCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExpressionImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 12;

  /**
   * The feature id for the '<em><b>Accessed Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__ACCESSED_DATA = 0;

  /**
   * The feature id for the '<em><b>Accessed Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__ACCESSED_FIELD = 1;

  /**
   * The feature id for the '<em><b>If Logic Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__IF_LOGIC_EXP = 2;

  /**
   * The feature id for the '<em><b>Then Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__THEN_EXP = 3;

  /**
   * The feature id for the '<em><b>Else Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__ELSE_EXP = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__NAME = 5;

  /**
   * The feature id for the '<em><b>Binding</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__BINDING = 6;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__BODY = 7;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.NewInputImpl <em>New Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.NewInputImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getNewInput()
   * @generated
   */
  int NEW_INPUT = 13;

  /**
   * The feature id for the '<em><b>Accessed Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_INPUT__ACCESSED_DATA = EXPRESSION__ACCESSED_DATA;

  /**
   * The feature id for the '<em><b>Accessed Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_INPUT__ACCESSED_FIELD = EXPRESSION__ACCESSED_FIELD;

  /**
   * The feature id for the '<em><b>If Logic Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_INPUT__IF_LOGIC_EXP = EXPRESSION__IF_LOGIC_EXP;

  /**
   * The feature id for the '<em><b>Then Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_INPUT__THEN_EXP = EXPRESSION__THEN_EXP;

  /**
   * The feature id for the '<em><b>Else Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_INPUT__ELSE_EXP = EXPRESSION__ELSE_EXP;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_INPUT__NAME = EXPRESSION__NAME;

  /**
   * The feature id for the '<em><b>Binding</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_INPUT__BINDING = EXPRESSION__BINDING;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_INPUT__BODY = EXPRESSION__BODY;

  /**
   * The feature id for the '<em><b>New Array Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_INPUT__NEW_ARRAY_ID = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>New Array Ids</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_INPUT__NEW_ARRAY_IDS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>New Array Exps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_INPUT__NEW_ARRAY_EXPS = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>New Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_INPUT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.LogicExpImpl <em>Logic Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.LogicExpImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getLogicExp()
   * @generated
   */
  int LOGIC_EXP = 14;

  /**
   * The feature id for the '<em><b>Left Logic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP__LEFT_LOGIC = 0;

  /**
   * The feature id for the '<em><b>Right Logic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP__RIGHT_LOGIC = 1;

  /**
   * The number of structural features of the '<em>Logic Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.PlusImpl <em>Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.PlusImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getPlus()
   * @generated
   */
  int PLUS = 15;

  /**
   * The feature id for the '<em><b>Accessed Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__ACCESSED_DATA = EXPRESSION__ACCESSED_DATA;

  /**
   * The feature id for the '<em><b>Accessed Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__ACCESSED_FIELD = EXPRESSION__ACCESSED_FIELD;

  /**
   * The feature id for the '<em><b>If Logic Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__IF_LOGIC_EXP = EXPRESSION__IF_LOGIC_EXP;

  /**
   * The feature id for the '<em><b>Then Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__THEN_EXP = EXPRESSION__THEN_EXP;

  /**
   * The feature id for the '<em><b>Else Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__ELSE_EXP = EXPRESSION__ELSE_EXP;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__NAME = EXPRESSION__NAME;

  /**
   * The feature id for the '<em><b>Binding</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__BINDING = EXPRESSION__BINDING;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__BODY = EXPRESSION__BODY;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.MinusImpl <em>Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.MinusImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getMinus()
   * @generated
   */
  int MINUS = 16;

  /**
   * The feature id for the '<em><b>Accessed Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__ACCESSED_DATA = EXPRESSION__ACCESSED_DATA;

  /**
   * The feature id for the '<em><b>Accessed Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__ACCESSED_FIELD = EXPRESSION__ACCESSED_FIELD;

  /**
   * The feature id for the '<em><b>If Logic Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__IF_LOGIC_EXP = EXPRESSION__IF_LOGIC_EXP;

  /**
   * The feature id for the '<em><b>Then Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__THEN_EXP = EXPRESSION__THEN_EXP;

  /**
   * The feature id for the '<em><b>Else Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__ELSE_EXP = EXPRESSION__ELSE_EXP;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__NAME = EXPRESSION__NAME;

  /**
   * The feature id for the '<em><b>Binding</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__BINDING = EXPRESSION__BINDING;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__BODY = EXPRESSION__BODY;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.MultImpl <em>Mult</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.MultImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getMult()
   * @generated
   */
  int MULT = 17;

  /**
   * The feature id for the '<em><b>Accessed Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__ACCESSED_DATA = EXPRESSION__ACCESSED_DATA;

  /**
   * The feature id for the '<em><b>Accessed Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__ACCESSED_FIELD = EXPRESSION__ACCESSED_FIELD;

  /**
   * The feature id for the '<em><b>If Logic Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__IF_LOGIC_EXP = EXPRESSION__IF_LOGIC_EXP;

  /**
   * The feature id for the '<em><b>Then Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__THEN_EXP = EXPRESSION__THEN_EXP;

  /**
   * The feature id for the '<em><b>Else Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__ELSE_EXP = EXPRESSION__ELSE_EXP;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__NAME = EXPRESSION__NAME;

  /**
   * The feature id for the '<em><b>Binding</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__BINDING = EXPRESSION__BINDING;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__BODY = EXPRESSION__BODY;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Mult</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.DivideImpl <em>Divide</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.exTwentyOne.impl.DivideImpl
   * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getDivide()
   * @generated
   */
  int DIVIDE = 18;

  /**
   * The feature id for the '<em><b>Accessed Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__ACCESSED_DATA = EXPRESSION__ACCESSED_DATA;

  /**
   * The feature id for the '<em><b>Accessed Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__ACCESSED_FIELD = EXPRESSION__ACCESSED_FIELD;

  /**
   * The feature id for the '<em><b>If Logic Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__IF_LOGIC_EXP = EXPRESSION__IF_LOGIC_EXP;

  /**
   * The feature id for the '<em><b>Then Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__THEN_EXP = EXPRESSION__THEN_EXP;

  /**
   * The feature id for the '<em><b>Else Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__ELSE_EXP = EXPRESSION__ELSE_EXP;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__NAME = EXPRESSION__NAME;

  /**
   * The feature id for the '<em><b>Binding</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__BINDING = EXPRESSION__BINDING;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__BODY = EXPRESSION__BODY;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Divide</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Program#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Program#getName()
   * @see #getProgram()
   * @generated
   */
  EAttribute getProgram_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.exTwentyOne.Program#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Program#getDeclarations()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Declarations();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Function#getLambda <em>Lambda</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lambda</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Function#getLambda()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Lambda();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Lambda <em>Lambda</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lambda</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Lambda
   * @generated
   */
  EClass getLambda();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Lambda#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Lambda#getName()
   * @see #getLambda()
   * @generated
   */
  EAttribute getLambda_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Lambda#getLambdaExp <em>Lambda Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lambda Exp</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Lambda#getLambdaExp()
   * @see #getLambda()
   * @generated
   */
  EReference getLambda_LambdaExp();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Input#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Input#getName()
   * @see #getInput()
   * @generated
   */
  EAttribute getInput_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Node#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Node#getName()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.exTwentyOne.Node#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Function</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Node#getFunction()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Function();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Node#getLambda <em>Lambda</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lambda</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Node#getLambda()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Lambda();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Stream <em>Stream</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stream</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Stream
   * @generated
   */
  EClass getStream();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.exTwentyOne.Stream#getInputsOrNodes <em>Inputs Or Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Inputs Or Nodes</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Stream#getInputsOrNodes()
   * @see #getStream()
   * @generated
   */
  EReference getStream_InputsOrNodes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.exTwentyOne.Stream#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Stream#getElements()
   * @see #getStream()
   * @generated
   */
  EReference getStream_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Element#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Element</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Element#getElement()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Element();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.exTwentyOne.Element#getNode <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Node</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Element#getNode()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Node();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Element#getOutput <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Output</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Element#getOutput()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Output();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.DataDecl <em>Data Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Decl</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.DataDecl
   * @generated
   */
  EClass getDataDecl();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.DataDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.DataDecl#getName()
   * @see #getDataDecl()
   * @generated
   */
  EAttribute getDataDecl_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.exTwentyOne.DataDecl#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Data</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.DataDecl#getData()
   * @see #getDataDecl()
   * @generated
   */
  EAttribute getDataDecl_Data();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.InputOrNode <em>Input Or Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input Or Node</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.InputOrNode
   * @generated
   */
  EClass getInputOrNode();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.NodeOrFunction <em>Node Or Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node Or Function</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.NodeOrFunction
   * @generated
   */
  EClass getNodeOrFunction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Expression#getAccessedData <em>Accessed Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Accessed Data</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Expression#getAccessedData()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_AccessedData();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Expression#getAccessedField <em>Accessed Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Accessed Field</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Expression#getAccessedField()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_AccessedField();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Expression#getIfLogicExp <em>If Logic Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>If Logic Exp</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Expression#getIfLogicExp()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_IfLogicExp();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Expression#getThenExp <em>Then Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then Exp</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Expression#getThenExp()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_ThenExp();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Expression#getElseExp <em>Else Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else Exp</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Expression#getElseExp()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_ElseExp();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.Expression#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Expression#getName()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Expression#getBinding <em>Binding</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Binding</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Expression#getBinding()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Binding();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Expression#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Expression#getBody()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Body();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.NewInput <em>New Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>New Input</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.NewInput
   * @generated
   */
  EClass getNewInput();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.exTwentyOne.NewInput#getNewArrayId <em>New Array Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>New Array Id</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.NewInput#getNewArrayId()
   * @see #getNewInput()
   * @generated
   */
  EAttribute getNewInput_NewArrayId();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.exTwentyOne.NewInput#getNewArrayIds <em>New Array Ids</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>New Array Ids</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.NewInput#getNewArrayIds()
   * @see #getNewInput()
   * @generated
   */
  EAttribute getNewInput_NewArrayIds();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.exTwentyOne.NewInput#getNewArrayExps <em>New Array Exps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>New Array Exps</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.NewInput#getNewArrayExps()
   * @see #getNewInput()
   * @generated
   */
  EReference getNewInput_NewArrayExps();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.LogicExp <em>Logic Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logic Exp</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.LogicExp
   * @generated
   */
  EClass getLogicExp();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.LogicExp#getLeftLogic <em>Left Logic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left Logic</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.LogicExp#getLeftLogic()
   * @see #getLogicExp()
   * @generated
   */
  EReference getLogicExp_LeftLogic();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.LogicExp#getRightLogic <em>Right Logic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right Logic</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.LogicExp#getRightLogic()
   * @see #getLogicExp()
   * @generated
   */
  EReference getLogicExp_RightLogic();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Plus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Plus
   * @generated
   */
  EClass getPlus();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Plus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Plus#getLeft()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Plus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Plus#getRight()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Minus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Minus</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Minus
   * @generated
   */
  EClass getMinus();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Minus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Minus#getLeft()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Minus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Minus#getRight()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Mult <em>Mult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mult</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Mult
   * @generated
   */
  EClass getMult();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Mult#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Mult#getLeft()
   * @see #getMult()
   * @generated
   */
  EReference getMult_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Mult#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Mult#getRight()
   * @see #getMult()
   * @generated
   */
  EReference getMult_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.exTwentyOne.Divide <em>Divide</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Divide</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Divide
   * @generated
   */
  EClass getDivide();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Divide#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Divide#getLeft()
   * @see #getDivide()
   * @generated
   */
  EReference getDivide_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.exTwentyOne.Divide#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.mydsl.exTwentyOne.Divide#getRight()
   * @see #getDivide()
   * @generated
   */
  EReference getDivide_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ExTwentyOneFactory getExTwentyOneFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ProgramImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM__NAME = eINSTANCE.getProgram_Name();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__DECLARATIONS = eINSTANCE.getProgram_Declarations();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.DeclarationImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ParameterImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.FunctionImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '<em><b>Lambda</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__LAMBDA = eINSTANCE.getFunction_Lambda();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.LambdaImpl <em>Lambda</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.LambdaImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getLambda()
     * @generated
     */
    EClass LAMBDA = eINSTANCE.getLambda();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LAMBDA__NAME = eINSTANCE.getLambda_Name();

    /**
     * The meta object literal for the '<em><b>Lambda Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAMBDA__LAMBDA_EXP = eINSTANCE.getLambda_LambdaExp();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.InputImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT__NAME = eINSTANCE.getInput_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.NodeImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__NAME = eINSTANCE.getNode_Name();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__FUNCTION = eINSTANCE.getNode_Function();

    /**
     * The meta object literal for the '<em><b>Lambda</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__LAMBDA = eINSTANCE.getNode_Lambda();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.StreamImpl <em>Stream</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.StreamImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getStream()
     * @generated
     */
    EClass STREAM = eINSTANCE.getStream();

    /**
     * The meta object literal for the '<em><b>Inputs Or Nodes</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STREAM__INPUTS_OR_NODES = eINSTANCE.getStream_InputsOrNodes();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STREAM__ELEMENTS = eINSTANCE.getStream_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ElementImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__ELEMENT = eINSTANCE.getElement_Element();

    /**
     * The meta object literal for the '<em><b>Node</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__NODE = eINSTANCE.getElement_Node();

    /**
     * The meta object literal for the '<em><b>Output</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__OUTPUT = eINSTANCE.getElement_Output();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.DataDeclImpl <em>Data Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.DataDeclImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getDataDecl()
     * @generated
     */
    EClass DATA_DECL = eINSTANCE.getDataDecl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_DECL__NAME = eINSTANCE.getDataDecl_Name();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_DECL__DATA = eINSTANCE.getDataDecl_Data();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.InputOrNodeImpl <em>Input Or Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.InputOrNodeImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getInputOrNode()
     * @generated
     */
    EClass INPUT_OR_NODE = eINSTANCE.getInputOrNode();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.NodeOrFunctionImpl <em>Node Or Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.NodeOrFunctionImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getNodeOrFunction()
     * @generated
     */
    EClass NODE_OR_FUNCTION = eINSTANCE.getNodeOrFunction();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExpressionImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Accessed Data</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__ACCESSED_DATA = eINSTANCE.getExpression_AccessedData();

    /**
     * The meta object literal for the '<em><b>Accessed Field</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__ACCESSED_FIELD = eINSTANCE.getExpression_AccessedField();

    /**
     * The meta object literal for the '<em><b>If Logic Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__IF_LOGIC_EXP = eINSTANCE.getExpression_IfLogicExp();

    /**
     * The meta object literal for the '<em><b>Then Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__THEN_EXP = eINSTANCE.getExpression_ThenExp();

    /**
     * The meta object literal for the '<em><b>Else Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__ELSE_EXP = eINSTANCE.getExpression_ElseExp();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__NAME = eINSTANCE.getExpression_Name();

    /**
     * The meta object literal for the '<em><b>Binding</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__BINDING = eINSTANCE.getExpression_Binding();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__BODY = eINSTANCE.getExpression_Body();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.NewInputImpl <em>New Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.NewInputImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getNewInput()
     * @generated
     */
    EClass NEW_INPUT = eINSTANCE.getNewInput();

    /**
     * The meta object literal for the '<em><b>New Array Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NEW_INPUT__NEW_ARRAY_ID = eINSTANCE.getNewInput_NewArrayId();

    /**
     * The meta object literal for the '<em><b>New Array Ids</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NEW_INPUT__NEW_ARRAY_IDS = eINSTANCE.getNewInput_NewArrayIds();

    /**
     * The meta object literal for the '<em><b>New Array Exps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEW_INPUT__NEW_ARRAY_EXPS = eINSTANCE.getNewInput_NewArrayExps();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.LogicExpImpl <em>Logic Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.LogicExpImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getLogicExp()
     * @generated
     */
    EClass LOGIC_EXP = eINSTANCE.getLogicExp();

    /**
     * The meta object literal for the '<em><b>Left Logic</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGIC_EXP__LEFT_LOGIC = eINSTANCE.getLogicExp_LeftLogic();

    /**
     * The meta object literal for the '<em><b>Right Logic</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGIC_EXP__RIGHT_LOGIC = eINSTANCE.getLogicExp_RightLogic();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.PlusImpl <em>Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.PlusImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getPlus()
     * @generated
     */
    EClass PLUS = eINSTANCE.getPlus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__LEFT = eINSTANCE.getPlus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__RIGHT = eINSTANCE.getPlus_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.MinusImpl <em>Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.MinusImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getMinus()
     * @generated
     */
    EClass MINUS = eINSTANCE.getMinus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__LEFT = eINSTANCE.getMinus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__RIGHT = eINSTANCE.getMinus_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.MultImpl <em>Mult</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.MultImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getMult()
     * @generated
     */
    EClass MULT = eINSTANCE.getMult();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULT__LEFT = eINSTANCE.getMult_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULT__RIGHT = eINSTANCE.getMult_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.exTwentyOne.impl.DivideImpl <em>Divide</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.exTwentyOne.impl.DivideImpl
     * @see org.xtext.example.mydsl.exTwentyOne.impl.ExTwentyOnePackageImpl#getDivide()
     * @generated
     */
    EClass DIVIDE = eINSTANCE.getDivide();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVIDE__LEFT = eINSTANCE.getDivide_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVIDE__RIGHT = eINSTANCE.getDivide_Right();

  }

} //ExTwentyOnePackage
