/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.exTwentyOne;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logic Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.exTwentyOne.LogicExp#getLeftLogic <em>Left Logic</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.exTwentyOne.LogicExp#getRightLogic <em>Right Logic</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.exTwentyOne.ExTwentyOnePackage#getLogicExp()
 * @model
 * @generated
 */
public interface LogicExp extends EObject
{
  /**
   * Returns the value of the '<em><b>Left Logic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left Logic</em>' containment reference.
   * @see #setLeftLogic(Expression)
   * @see org.xtext.example.mydsl.exTwentyOne.ExTwentyOnePackage#getLogicExp_LeftLogic()
   * @model containment="true"
   * @generated
   */
  Expression getLeftLogic();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.exTwentyOne.LogicExp#getLeftLogic <em>Left Logic</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left Logic</em>' containment reference.
   * @see #getLeftLogic()
   * @generated
   */
  void setLeftLogic(Expression value);

  /**
   * Returns the value of the '<em><b>Right Logic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right Logic</em>' containment reference.
   * @see #setRightLogic(Expression)
   * @see org.xtext.example.mydsl.exTwentyOne.ExTwentyOnePackage#getLogicExp_RightLogic()
   * @model containment="true"
   * @generated
   */
  Expression getRightLogic();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.exTwentyOne.LogicExp#getRightLogic <em>Right Logic</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right Logic</em>' containment reference.
   * @see #getRightLogic()
   * @generated
   */
  void setRightLogic(Expression value);

} // LogicExp
