/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.exTwentyOne.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.exTwentyOne.ExTwentyOnePackage;
import org.xtext.example.mydsl.exTwentyOne.InputOrNode;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Input Or Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InputOrNodeImpl extends MinimalEObjectImpl.Container implements InputOrNode
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InputOrNodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExTwentyOnePackage.Literals.INPUT_OR_NODE;
  }

} //InputOrNodeImpl
